server:
  port: 80
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/student_society?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.mouxianyu.studentsociety.pojo.entity

mouxianyu:
  img-path:
    activity: E:\\kingsme\\Documents\\瑞幸电脑拷贝\\毕设\\项目\\img\\activity\\
    avatar: E:\\kingsme\\Documents\\瑞幸电脑拷贝\\毕设\\项目\\img\\avatar\\
    society: E:\\kingsme\\Documents\\瑞幸电脑拷贝\\毕设\\项目\\img\\society\\
    news: E:\\kingsme\\Documents\\瑞幸电脑拷贝\\毕设\\项目\\img\\news\\