server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_society
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.mouxianyu.studentsociety.pojo.entity